name: Build Variables

on:
  workflow_call:
    outputs:
      branch:
        value: ${{ jobs.build-variables.outputs.branch }}
      commit:
        value: ${{ jobs.build-variables.outputs.commit }}

jobs:
  build-variables:
    runs-on:
      - self-hosted
      - Linux

    outputs:
      branch: ${{ steps.branch_name.outputs.proj_var }}
      commit: ${{ steps.commit_sha.outputs.proj_var }}

    steps:
      - name: Branch Name
        id: branch_name
        run: echo "proj_var=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
        
      - name: Branch Name
        id: commit_sha
        run: echo "proj_var=${{ github.sha }}" >> "$GITHUB_OUTPUT"