name: CI Build

on: push

jobs:
  compile:
    name: Compile Project
    uses: ./.github/workflows/compile-project.yml

  package:
    name: Package Project
    runs-on:
      - self-hosted
      - Linux

    needs:
      - compile

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      OUTPUT_NAME: "${{ github.sha }}-packed"

    outputs:
      artifact-name: ${{ env.OUTPUT_NAME }}
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact-upload.outputs.artifact-url }}

    steps:
      - name: Download artifact
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.compile.outputs.artifact-name }}

      - name: Upload artifact
        id: artifact-upload
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: |
            package.json
            package-lock.json
            assets/
            dist/
            ptero/

  release:
    name: Release Project
    runs-on:
      - self-hosted
      - Linux

    needs:
      - package

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      OUTPUT_NAME: "${{ github.sha }}-packed"

    steps:
      - name: Download artifact
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        run: wget ${{ needs.package.outputs.artifact-url }}
      
      - name: Copy artifact
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        run: cp "artifacts/${{ env.OUTPUT_NAME }}.zip" "artifacts/pterodactyl-package.zip"

      - name: Create release
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.OUTPUT_NAME }}.zip
            pterodactyl-package.zip
