name: CI Build

on: push

jobs:
  compile:
    name: Compile Project
    uses: ./.github/workflows/compile-project.yml

  package:
    name: Package Project
    runs-on:
      - self-hosted
      - Linux

    needs:
      - compile

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      OUTPUT_NAME: "${{ github.sha }}-packed"

    steps:
      - name: Download artifact
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.compile.outputs.artifact-name }}

      - name: Upload artifact
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: |
            package.json
            package-lock.json
            assets/
            dist/
            ptero/