name: CI Build

on:
  push:
    branches:
      - "main"
      - "master"
      - "feature/**"

jobs:
  dump_contexts_to_log:
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build:
    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Test Echi
        run: echo "$github.base_ref"

      - name: Upload artifact
        if: ${{ github.base_ref == 'main' || github.base_ref == 'master' }}
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifact
          path: |
            package.json
            package-lock.json
            assets/
            dist/
            ptero/
          overwrite: true