name: CI Build

on:
  push:
    branches:
      - "main"
      - "master"
      - "feature/**"

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        if: ${{ github.base_ref == 'main' || github.base_ref == 'master' }}
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifact
          path: |
            package.json
            package-lock.json
            assets/
            dist/
            ptero/
          overwrite: true