name: Compile Project

on:
  workflow_call:
    outputs:
      artifact-name:
        value: Compiled Project
      artifact-id:
        value: ${{ jobs.compile-project.outputs.artifact-id }}
      artifact-url:
        value: ${{ jobs.compile-project.outputs.artifact-url }}

jobs:
  compile-project:
    runs-on:
      - self-hosted
      - Linux

    outputs:
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact-upload.outputs.artifact-url }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Compile project
        run: npm run build

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: Compiled Project
          retention-days: 1
          path: ./*