name: Compile Project

on:
  workflow_call:
    outputs:
      artifact-name:
        value: ${{ jobs.compile-project.outputs.artifact-name }}
      artifact-id:
        value: ${{ jobs.compile-project.outputs.artifact-id }}
      artifact-url:
        value: ${{ jobs.compile-project.outputs.artifact-url }}
      bumped-version:
        value: ${{ jobs.compile-project.outputs.bumped-version }}

jobs:
  bump-version:
    name: Bump Version
    uses: ./.github/workflows/version-bump.yml

  compile-project:
    name: Compile Project
    runs-on:
      - self-hosted
      - Linux

    needs:
      - bump-version

    env:
      OUTPUT_NAME: "${{ github.sha }}-compiled"

    outputs:
      artifact-name: ${{ env.OUTPUT_NAME }}
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact-upload.outputs.artifact-url }}
      bumped-version: ${{ needs.bump-version.outputs.bumped-version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Compile project
        run: npm run build

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: ${{ env.OUTPUT_NAME }}
          retention-days: 1
          path: ./*