name: PR Author Assignment

on:
  pull_request_target:
    types:
      - opened
      - reopened
  
permissions:
  pull-requests: write
  
jobs:
  assign-author:
    name: Assign PR Author
    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Author auto assignemnt
        uses: toshimaru/auto-author-assign@v2.1.0