name: Pterodactyl Restart

on:
  release:
    types:
      - published

jobs:
  restart-panel:
    name: Restart Panel

    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Run script
        run: node .github/scripts/ptero-restart.js ${{ secrets.PTERO_API_KEY }}