name: Version Bump Prod

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**"
      - "!package.json"

jobs:
  version-bump:
    name: Bump Version
    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Bump package version
        run: node .github/scripts/version-bump-prod.js

      - name: Push package.json
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(npm): Bumped package version"
          committer_name: Version Bumper
          committer_email: github-actions[bot]@users.noreply.github.com
          add: "package.json"