name: Version Bump

on:
  workflow_call:
    outputs:
      bumped-version:
        value: ${{ jobs.compile-project.outputs.bumped-version }}

jobs:
  compile-project:
    name: Bump Version
    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'develop' }}
    runs-on:
      - self-hosted
      - Linux

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    outputs:
      bumped-version: ${{ steps.load-package-data.outputs.bumped-version }}

    steps:
      - name: Checkout Repo
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'develop' }}
        uses: actions/checkout@v4

      - name: Setup Node
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'develop' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Bump package version (beta)
        if: ${{ env.BRANCH_NAME == 'develop' }}
        run: node .github/scripts/version-bump-beta.js

      - name: Bump package version (prod)
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' }}
        run: node .github/scripts/version-bump-prod.js

      - name: Push package.json
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'develop' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(npm): Bumped package version"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: "package.json"

      - name: Load package.json into the env
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'develop' }}
        id: load-package-data
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "bumped-version=${{ fromJson(env.PACKAGE_JSON).version }}" >> "$GITHUB_OUTPUT"